version: "3.2.0"

trading_modes:
  - id: "mt5"
    enabled: true
    brokerType: "metatrader"
    mtType: "mt5"
    mtLogin: 168516134
    mtPassword: "Anam.cool65"
    mtServer: "XMGlobal-MT5 2"
    mtAccountType: "demo"
    mtBroker: "XMGlobal"